apiVersion: v1
kind: Service
metadata:
  name: myblog-hugo-service
spec:
  selector:
    app: myblog
    component: hugo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # 只需要集群内部访问
