apiVersion: v1
kind: Service
metadata:
  name: myblog-status-service
spec:
  selector:
    app: myblog
    component: status
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
